forms/game.py
from flask_wtf import FlaskForm
from wtforms import *
from wtforms.validators import DataRequired


class UniteForm(FlaskForm):
    first = StringField('Карта 1', validators=[DataRequired()])
    second = StringField('Карта 2', validators=[DataRequired()])
    submit = SubmitField('Объединить')

views/game.py
from flask import current_app as app
from flask import redirect, url_for, render_template, Blueprint
from flask_login import login_required, current_user
from data import db_session
from forms.game import UniteForm
from data.__all_models import Card, User, CardView

blueprint = Blueprint('game', __name__)


@blueprint.route('/game', methods=['GET', 'POST'])
def main_game():
    params = dict()
    if current_user.is_authenticated:
        params['form'] = UniteForm()
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.id == current_user.id).first()
        if params['form'].validate_on_submit():
            card1 = int(params['form'].first.data)
            card2 = int(params['form'].second.data)
            card = db_sess.query(Card).filter(Card.first_creation_component == card1).filter(
                Card.second_creation_component == card2).first()
            if not card:
                card = db_sess.query(Card).filter(Card.first_creation_component == card2).filter(
                    Card.second_creation_component == card1).first()
            if not card:
                params['message'] = "К сожалению, мы не можем объединить эти две сферы"
            elif card not in user.cards:
                user.cards.append(card)
                db_sess.merge(user)
                db_sess.commit()
        profs = list()
        for card in user.cards:
            d = CardView(card)
            profs.append(d)
        params['cards'] = profs
        return render_template('Navigator/game.html', **params)
    else:
        return render_template('exceptions/auth_exception.html', **params)

views/navigator.py
from flask import current_app as app
from flask import redirect, url_for, render_template, Blueprint
from data import db_session
from data.__all_models import Card, CardView

blueprint = Blueprint('navigator', __name__)


@blueprint.route('/about')
def about():
    params = dict()
    return render_template('Navigator/about.html', **params)


@blueprint.route('/scope/<int:card>')
def scope(card: int):
    pass


@blueprint.route('/profession/all')
def professions():
    params = dict()
    return render_template("Navigator/all_professions.html", **params)
@blueprint.route('/profession/WEB')
def WEB():
    params = dict()
    return render_template("Navigator/WEB.html", **params)

@blueprint.route('/profession/game_dev')
def game_dev():
    params = dict()
    return render_template("Navigator/game_dev.html", **params)

@blueprint.route('/profession/data_science')
def data_science():
    params = dict()
    return render_template("Navigator/data_science.html", **params)

@blueprint.route('/profession/<int:card>')
def profession(card: int):
    params = dict()
    db_sess = db_session.create_session()
    card = db_sess.query(Card).filter(Card.id == card).first()
    params['card'] = CardView(card)
    return render_template("Navigator/profession.html", **params)

templates/Navigator/WEB.html
{% extends "base.html" %}

{% block content %}
    <section class="hero d-flex flex-column align-items-center justify-content-center">
      <div class="text-center">
        <h1 class="h1 text-white fw-medium fst-italic">Веб разработчики</h1>
        <h2 class="display-3 text-white fw-bold"> Делятся на два основных класса<br /> Front-end / Back-end</h2>
        <a href="#skills" class="btn btn-lg fs-6 fw-medium mt-5 btn-primary p-3">Подробнее</a>
      </div>
    </section>

    <!-- Skills Section -->
    <section class="container py-5" id="skills">
      <div class="row mt-4 py-3">
        <div class="col-12 d-flex flex-column text-center justify-content-center">
          <h2>SKILLS</h2>
        </div>
      </div>
      <div class="row d-flex justify-content-between mx-0">
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-cart-shopping"></i>
          <h3 class="bigtext_WEB">Примеры</h3>
          <p class="smalltext_WEB">Почти любая современная разработка имеет веб-версию. Вы будете писать как простые и понятные вещи, вроде интернет магазинов, но возможности веб разработчиков почти безграничны, и вы сможете запустить здесь. Все что придёт вам в голову</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-laptop"></i>
          <h3 class="bigtext_WEB">Front-end Development</h3>
          <p class="smalltext_WEB">Знание JS Ts html/css WebAsm Вакансии Зарубеж (86255 jobs) СНГ (4788jobs) Зарплаты Junior - 70k+ Midle - 170k+ Senjor - 300k+</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-mobile-screen-button"></i>
          <h3 class="bigtext_WEB">Back-end Development</h3>
          <p class="smalltext_WEB">Знание Go JS Java/C# Python php sql Вакансии Зарубеж (112701 jobs) СНГ (5611jobs) Зарплаты Junior - 120k+ Midle - 250k+ Senjor - 450k+</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-mobile-screen-button"></i>
          <h3 class="bigtext_WEB">Умения</h3>
          <p class="smalltext_WEB">Относительно лёгкий вход. Много годных бесплатных материалов. Огромное сообщество. Сложно переключаться в другую ветвь разработки</p>
        </div>
      </div>
      <a href="/profession/all" class="btn btn-lg fs-6 fw-medium mt-5 btn-primary p-3">Вернуться к выбору профессий</a>
    </section>

{% endblock %}

templates/Navigator/about.html
{% extends "base.html" %}

{% block content %}

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/about.css')}}">
    <title>{{ title }}</title>
</head>
<body>
	<section class="about">
		<h1>О НАС</h1>
		<p style="font-weight: bold">
		Начни с этого....
		</p>
		<div class="about-info">
			<div class="about-img">
				<img src="{{url_for('static', filename='img/logo.png')}}" alt="Geeksforgeeks">
			</div>
			<div>
			<p> Lorem Ipsum is a leading platform
				that provides computer science resources
				and coding challenges for programmers and
				technology enthusiasts,along with interview
				and exam preparations for upcoming aspirants.
				With a strong emphasis on enhancing coding skills
				and knowledge,it has become a trusted destination
				for over 12 million plus registered users worldwide.
			</p>
			</div>
		</div>
	</section>

	<section class="team">
		<h1>Команда проекта</h1>
		<div class="team-cards">
			<div class="card">
				<div class="card-img">
					<img src="{{url_for('static', filename='img/about/Dima.png')}}" alt="Dima">
				</div>
				<div class="card-info">
					<h2 class="card-name">Дмитрий Ряжских</h2>
					<p class="card-role"></p>
					<p class="card-email">rya</p>
					<p><button class="button">Contact</button></p>
				</div>
			</div>

			<div class="card">
				<div class="card-img">
					<img src="{{url_for('static', filename='img/about/Matvey.png')}}" alt="Matvey">
				</div>
				<div class="card-info">
					<h2 class="card-name">Матвей Мягков</h2>
					<p class="card-role"></p>
					<p class="card-email"></p>
					<p><button class="button">Contact</button></p>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<p>© 2024 StartTeam. All Rights Reserved.</p>
	</footer>
</body>

{% endblock %}

templates/Navigator/all_professions.html
{% extends "base.html" %}

{% block content %}
    <div class="body_all_prof">
        <div class="container_all_prof" >
            <div class="imagebox">
                <img src="{{url_for('static', filename='img/profile.png')}}" class="img1">
            </div>
            <span class="object_all_p objblue"></span>
            <span class="bigtext">GO</span>
            <div class="title">Веб программист</div>
            <div class="buySection">
                <h2><sup>$</sup>0<span></span></h2>
                <a href="/profession/WEB">
                    <button class="bluebtn">GET start</button>
                </a>
            </div>
        </div>

        <div class="container_all_prof" >
            <div class="imagebox">
                <img src="{{url_for('static', filename='img/profile.png')}}" class="img1">
            </div>
            <span class="object_all_p objred"></span>
            <span class="bigtext">GO</span>
            <div class="title">Gamedev</div>
            <div class="buySection">
                <h2><sup>$</sup>0<span></span></h2>
                <a href="/profession/game_dev">
                    <button class="redbtn">GET start</button>
                </a>
            </div>
        </div>

        <div class="container_all_prof" >
            <div class="imagebox">
                <img src="{{url_for('static', filename='img/profile.png')}}" class="img1">
            </div>
            <span class="object_all_p objviolete"></span>
            <span class="bigtext">GO</span>
            <div class="title">Data science, ML</div>
            <div class="buySection">
                <h2><sup>$</sup>0<span></span></h2>
                <a href="/profession/data_science">
                    <button class="violetebtn">GET start</button>
                </a>
            </div>
        </div>
        <div class="bgposter"></div>
    </div>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script><script  src="./script.js"></script>

{% endblock %}

templates/Navigator/data_science.html
{% extends "base.html" %}

{% block content %}
    <section class="hero d-flex flex-column align-items-center justify-content-center">
      <div class="text-center">
        <h1 class="h1 text-white fw-medium fst-italic">Data science, machine learning</h1>
        <a href="#skills" class="btn btn-lg fs-6 fw-medium mt-5 btn-primary p-3">Подробнее</a>
      </div>
    </section>

    <!-- Skills Section -->
    <section class="container py-5" id="skills">
      <div class="row mt-4 py-3">
        <div class="col-12 d-flex flex-column text-center justify-content-center">
          <h2>SKILLS</h2>
        </div>
      </div>
      <div class="row d-flex justify-content-between mx-0">
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-cart-shopping"></i>
          <h3 class="bigtext_WEB">Примеры</h3>
          <p class="smalltext_WEB">Стихия будущего. Анализ данных, машинное обучение, нейронные сети, наука о данных. Все эти понятия связаны между собой, и формируют отдельный, порой кажется особенный мир, в котором проходят самые невероятные открытия.</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-laptop"></i>
          <h3 class="bigtext_WEB">Высокий и низкий уровень</h3>
          <p class="smalltext_WEB">Завязана на Python и двух мощнейших технологиях Fortran Rust</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-mobile-screen-button"></i>
          <h3 class="bigtext_WEB">Статы</h3>
          <p class="smalltext_WEB">Высочайшая востребованность. Много вакансий 80k+/35k+. Зарплаты 80k+/190k+/500k+</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-mobile-screen-button"></i>
          <h3 class="bigtext_WEB">Умения</h3>
          <p class="smalltext_WEB">Хорошая база. Много материала для обучения. Высокий порог входа</p>
        </div>
      </div>
      <a href="/profession/all" class="btn btn-lg fs-6 fw-medium mt-5 btn-primary p-3">Вернуться к выбору профессий</a>
    </section>

{% endblock %}

templates/Navigator/game.html
{% extends "base.html" %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
</head>
<style class="hover"></style>
<div class="swiper mySwiper">
    <div class="swiper-wrapper">
        {% for card in cards %}
        <div class="card nft swiper-slide" id="{{ card.id }}">
            <div class='main'>
              <img class='tokenImage' src="{{ url_for('static', filename=card.img) }}" alt="IMG" />
              <a href="{{ url_for('navigator.profession', card=card.id) }}"><h2>{{ card.name }}</h2></a>
              <div class='tokenInfo'>
                <div class="about">
                  <p>{{ card.about }}</p>
                </div>
              </div>
              <div class='creator'>
                <div class='wrapper'>
                  <img src="{{ url_for('static', filename=card.field_img) }}" alt="Shape" />
                </div>
                <p><ins>сфера</ins> {{ card.field }}</p>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div>
  </div>


  <form action="" method="post" id="unite">
      {{ form.hidden_tag() }}
      <section class="demo">
          {{ form.first(type="text", class="first invisible") }}
          {{ form.second(type="text", class="second invisible") }}
        <div class="card first-card-operator" id="first"></div>
        <span class="operator">+</span>
        <div class="card second-card-operator" id="second"></div>
        <span class="operator">=</span>
        <div class="card"><span>?</span></div>
      </section>
      <p>{{ form.submit(type="submit", class="btn mt-4", form="unite") }}</p>
                            {{message}}
  </form>

  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  <script>
    var swiper = new Swiper(".mySwiper", {
      slidesPerView: 3,
      spaceBetween: 30,
      pagination: {
        el: ".swiper-pagination",
        clickable: true,
      },
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
    });

    var x;
    var $cards = $(".card");
    var $style = $(".hover");

    $cards
      .on("mousemove touchmove", function(e) {
        // normalise touch/mouse
        var pos = [e.offsetX,e.offsetY];
        e.preventDefault();
        if ( e.type === "touchmove" ) {
          pos = [ e.touches[0].clientX, e.touches[0].clientY ];
        }
        var $card = $(this);
        // math for mouse position
        var l = pos[0];
        var t = pos[1];
        var h = $card.height();
        var w = $card.width();
        var px = Math.abs(Math.floor(100 / w * l)-100);
        var py = Math.abs(Math.floor(100 / h * t)-100);
        var pa = (50-px)+(50-py);
        // math for gradient / background positions
        var lp = (50+(px - 50)/1.5);
        var tp = (50+(py - 50)/1.5);
        var px_spark = (50+(px - 50)/7);
        var py_spark = (50+(py - 50)/7);
        var p_opc = 20+(Math.abs(pa)*1.5);
        var ty = ((tp - 50)/2) * -1.3;
        var tx = ((lp - 50)/1.5) * 1;
        var grad_pos = `background-position: ${lp}% ${tp}%;`
        var sprk_pos = `background-position: ${px_spark}% ${py_spark}%;`
        var opc = `opacity: ${p_opc/100};`
        var tf = `transform: rotateX(${ty}deg) rotateY(${tx}deg)`
        var style = `
          .card:hover:before { ${grad_pos} }
          .card:hover:after { ${sprk_pos} ${opc} }
        `
        $cards.removeClass("active");
        $card.removeClass("animated");
        $card.attr( "style", tf );
        $style.html(style);
        if ( e.type === "touchmove" ) {
          return false;
        }
        clearTimeout(x);
      }).on("mouseout touchend touchcancel", function() {
        var $card = $(this);
        $style.html("");
        $card.removeAttr("style");
        x = setTimeout(function() {
          $card.addClass("animated");
        },3500);
      });

     var $nft = $(".nft");
     var first = $(".first")[0];
     var second = $(".second")[0];
     var first_card_operator = $(".first-card-operator")[0];
     var second_card_operator = $(".second-card-operator")[0];

     $nft
        .on("click", function(e) {
            var $cur_nft = $(this)[0];
            if (first.value == $cur_nft.id || $cur_nft.id == "first") {
                first.value = null;
                first_card_operator.innerHTML = "";
                first_card_operator.classList.remove("nft");
            } else if (second.value == $cur_nft.id || $cur_nft.id == "second") {
                second.value = null;
                second_card_operator.innerHTML = "";
                second_card_operator.classList.remove("nft");
            } else if (!first.value) {
                first.value = $cur_nft.id;
                first_card_operator.innerHTML = $cur_nft.innerHTML;
                first_card_operator.classList.add("nft");
            } else {
                second.value = $cur_nft.id;
                second_card_operator.innerHTML = $cur_nft.innerHTML;
                second_card_operator.classList.add("nft");
            }
        });
  </script>
{% endblock %}

templates/Navigator/game_dev.html
{% extends "base.html" %}

{% block content %}
    <section class="hero d-flex flex-column align-items-center justify-content-center">
      <div class="text-center">
        <h1 class="h1 text-white fw-medium fst-italic">Разработчики игр</h1>
        <h2 class="display-3 text-white fw-bold"> Делятся на два основных класса<br /> Разработчики движков / Разработчики игр</h2>
        <a href="#skills" class="btn btn-lg fs-6 fw-medium mt-5 btn-primary p-3">Подробнее</a>
      </div>
    </section>

    <!-- Skills Section -->
    <section class="container py-5" id="skills">
      <div class="row mt-4 py-3">
        <div class="col-12 d-flex flex-column text-center justify-content-center">
          <h2>SKILLS</h2>
        </div>
      </div>
      <div class="row d-flex justify-content-between mx-0">
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-cart-shopping"></i>
          <h3 class="bigtext_WEB">Примеры</h3>
          <p class="smalltext_WEB">Стихия симбиоза инженера с игровым движком. Инди разработка отличается в масштабах, и зачастую можно встретить как 2-3 человека делают все, начаиная от движак вплоть до арта</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-laptop"></i>
          <h3 class="bigtext_WEB">Разработчики движков</h3>
          <p class="smalltext_WEB">Стихия воплощения всех законов физики и математики в виртуальный мир. Разработчики таких игровых движков как Unreal Engine, Unity создают возможности. Подсистемы: анимации, физика, эффекты, освещение, тени, 2D/3D. Знание Python/C++ Rust. Senjor - 600k+</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-mobile-screen-button"></i>
          <h3 class="bigtext_WEB">Разработчик игр</h3>
          <p class="smalltext_WEB">Art/UI/Механики/Анимации/Мультиплеер. Знание C++ C# JS Kotlin Swift Python. 80k+/170k+/300k+</p>
        </div>
        <div class="card mt-5 d-flex flex-column align-items-center text-center bg-white p-4" style="width: 25rem">
          <i class="text-white bg-primary d-flex align-items-center justify-content-center fs-2 rounded-circle fa-solid fa-mobile-screen-button"></i>
          <h3 class="bigtext_WEB">Умения</h3>
          <p class="smalltext_WEB">Зачастую интересная работа. Можно в соло сделать мировой продукт. Развита база. Высокий порог входа</p>
        </div>
      </div>
      <a href="/profession/all" class="btn btn-lg fs-6 fw-medium mt-5 btn-primary p-3">Вернуться к выбору профессий</a>
    </section>

{% endblock %}

templates/Navigator/main.html
{% extends "base.html" %}

{% block content %}
<div class="container_for_main">
    <a href="/profession/all" class="button button--piyo">
        <div class="button__wrapper">
            <span class="button__text">START</span>
        </div>
        <div class="characterBox">
            <div class="character wakeup">
                <div class="character__face"></div>
            </div>
            <div class="character wakeup">
                <div class="character__face"></div>
            </div>
            <div class="character">
                <div class="character__face"></div>
            </div>
        </div>
    </a>
</div>
{% endblock %}

templates/Navigator/profession.html
{% extends "base.html" %}

{% block content %}
<div class='main'>
  <img class='tokenImage' src="{{ url_for('static', filename=card.img) }}" alt="IMG" />
  <h2>{{ card.name }}</h2>
  <div class='tokenInfo'>
    <div class="about">
      <p>{{ card.about }}</p>
    </div>
  </div>
  <div class='creator'>
    <div class='wrapper'>
      <img src="{{ url_for('static', filename=card.field_img) }}" alt="Shape" />
    </div>
    <p><ins>сфера</ins> {{ card.field }}</p>
  </div>
</div>
{% endblock %}